### ISSUE TITLE
c * (t /= d) * t + b ???

### ISSUE THREAD

**Issue by ccorcos** [chenglou/tween-functions#3]
I'm so confused by this line:

https://github.com/chenglou/tween-functions/blob/master/index.js#L11

Why are you using `/=`?

**Comment by chenglou** [comment]
The code's literally taken from Robert Penner, who made these for flash a long long time ago.

`/=` is used because it mutates the value of `t`, which is used again subsequently. Less confusing way of doing this would be `c * (t / d) * (t / d) + b`.

Hope that helps!

**Comment by ccorcos** [comment]
I see. What a terrible way of writing code. lol

**Comment by chenglou** [comment]
Yeah not too clear. To be fair, that was a decade ago =)

**Comment by ccorcos** [comment]
> Variables with longer names take longer to look up than variables with short names, because of the interpreter’s internal hashing procedure.

http://gilmoreorless.github.io/sydjs-preso-easing/#min-actionscript

Looks like its just a relic of some flash quirks lol

**Comment by chenglou** [comment]
Ah yes, I remember that! =D
